// Monaco themes built from the app's design tokens (styles.css, hue 278°),
// so the editor reads as part of the app instead of a VS Code panel.
// Monaco needs hex, so these are the tokens converted from OKLCH.
import type * as Monaco from "monaco-editor";

export const EDITOR_THEME = { dark: "hexa-dark", light: "hexa-light" } as const;

export function defineEditorThemes(monaco: typeof Monaco) {
  monaco.editor.defineTheme(EDITOR_THEME.dark, {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "dcdde5" },
      { token: "comment", foreground: "777986", fontStyle: "italic" },
      { token: "keyword", foreground: "b0a2fe" },
      { token: "operator.sql", foreground: "b0a2fe" },
      { token: "operator", foreground: "a0a3b8" },
      { token: "delimiter", foreground: "a0a3b8" },
      { token: "string", foreground: "89d298" },
      { token: "number", foreground: "6ccdea" },
      { token: "predefined", foreground: "6bd8de" },
      { token: "identifier", foreground: "dcdde5" },
      { token: "identifier.quote", foreground: "a0a3b8" },
      { token: "type", foreground: "f2ad73" },
      { token: "string.key.json", foreground: "b0a2fe" },
      { token: "keyword.json", foreground: "f2ad73" },
      // FetchXML
      { token: "tag.xml", foreground: "b0a2fe" },
      { token: "attribute.name.xml", foreground: "f2ad73" },
      { token: "attribute.value.xml", foreground: "89d298" },
      { token: "delimiter.xml", foreground: "777986" },
    ],
    colors: {
      "editor.background": "#101119",
      "editor.foreground": "#dcdde5",
      "editor.lineHighlightBackground": "#171922",
      "editor.lineHighlightBorder": "#00000000",
      "editor.selectionBackground": "#313457",
      "editor.inactiveSelectionBackground": "#25273d",
      "editorCursor.foreground": "#98a2fc",
      "editorLineNumber.foreground": "#525461",
      "editorLineNumber.activeForeground": "#babdcb",
      "editorIndentGuide.background1": "#20222d",
      "editorWhitespace.foreground": "#2c2e3a",
      "editorWidget.background": "#171922",
      "editorWidget.border": "#363845",
      "editorSuggestWidget.background": "#171922",
      "editorSuggestWidget.border": "#363845",
      "editorSuggestWidget.selectedBackground": "#2a2c47",
      "editorSuggestWidget.highlightForeground": "#98a2fc",
      "editorHoverWidget.background": "#171922",
      "editorHoverWidget.border": "#363845",
      "editorBracketMatch.background": "#31345780",
      "editorBracketMatch.border": "#5a58df",
      "scrollbarSlider.background": "#36384580",
      "scrollbarSlider.hoverBackground": "#363845",
      "focusBorder": "#00000000",
    },
  });

  monaco.editor.defineTheme(EDITOR_THEME.light, {
    base: "vs",
    inherit: true,
    rules: [
      { token: "", foreground: "1f212e" },
      { token: "comment", foreground: "717480", fontStyle: "italic" },
      { token: "keyword", foreground: "6741ca" },
      { token: "operator.sql", foreground: "6741ca" },
      { token: "operator", foreground: "515466" },
      { token: "delimiter", foreground: "515466" },
      { token: "string", foreground: "21763c" },
      { token: "number", foreground: "006ca2" },
      { token: "predefined", foreground: "007386" },
      { token: "identifier", foreground: "1f212e" },
      { token: "identifier.quote", foreground: "515466" },
      { token: "type", foreground: "ad5600" },
      { token: "string.key.json", foreground: "6741ca" },
      { token: "keyword.json", foreground: "ad5600" },
      { token: "tag.xml", foreground: "6741ca" },
      { token: "attribute.name.xml", foreground: "ad5600" },
      { token: "attribute.value.xml", foreground: "21763c" },
      { token: "delimiter.xml", foreground: "717480" },
    ],
    colors: {
      "editor.background": "#ffffff",
      "editor.foreground": "#1f212e",
      "editor.lineHighlightBackground": "#f6f6fb",
      "editor.lineHighlightBorder": "#00000000",
      "editor.selectionBackground": "#d6dcff",
      "editor.inactiveSelectionBackground": "#e6e9fa",
      "editorCursor.foreground": "#524bda",
      "editorLineNumber.foreground": "#9c9ea8",
      "editorLineNumber.activeForeground": "#383a45",
      "editorIndentGuide.background1": "#ebecf3",
      "editorWidget.background": "#ffffff",
      "editorWidget.border": "#d5d7e0",
      "editorSuggestWidget.background": "#ffffff",
      "editorSuggestWidget.border": "#d5d7e0",
      "editorSuggestWidget.selectedBackground": "#e8e9fb",
      "editorSuggestWidget.highlightForeground": "#524bda",
      "editorHoverWidget.background": "#ffffff",
      "editorHoverWidget.border": "#d5d7e0",
      "editorBracketMatch.background": "#d6dcff80",
      "editorBracketMatch.border": "#524bda",
      "focusBorder": "#00000000",
    },
  });
}
